### ISSUE TITLE
mysqlのリレーションを貼った場合のエラーハンドリング

### ISSUE THREAD

**Issue by yasuto2002** [yasuto2002/todo-app#14]

**Comment by yasuto2002** [comment]
### to_do.category_idはcategory.idを参照するように制約をつける

```sql
ALTER TABLE `to_do` ADD FOREIGN KEY (`category_id`) REFERENCES `to_do_category` (`id`) 
```

すでに制約違反があると更新できない
```
ALTER TABLE `to_do` ADD FOREIGN KEY (`category_id`) REFERENCES `to_do_category` (`id`) ON UPDATE CASCADE;
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`to_do`.`#sql-1_2`, CONSTRAINT `#sql-1_2_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `to_do_category` (`id`) ON UPDATE CASCADE)
```

**Comment by yasuto2002** [comment]
## befor category削除

```scala
  def delete(categoryId:Long) = messagesAction.async { implicit req =>
    CategoryRepository.get(tag[Category][Long](categoryId)).flatMap(_ match {
      case Some(category) => {
          CategoryRepository.remove(category.id).map(_.fold{InternalServerError("Server Error")}{_ => Redirect(routes.CategoryController.index())})
      }
      case None => {
        Future.successful(BadRequest("Invalid value"))
      }
    })
  }
```

**Comment by yasuto2002** [comment]
### 参照エラー

```
Execution exception
[MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`to_do`.`to_do`, CONSTRAINT `to_do_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `to_do_category` (`id`) ON UPDATE CASCADE)]
```
コンソール
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`to_do`.`to_do`, CONSTRAINT `to_do_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `to_do_category` (`id`) ON UPDATE CASCADE)]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:332)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:251)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:421)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:417)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`to_do`.`to_do`, CONSTRAINT `to_do_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `to_do_category` (`id`) ON UPDATE CASCADE)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)

```

**Comment by yasuto2002** [comment]
### after  category削除

```scala
def delete(categoryId:Long) = messagesAction.async { implicit req =>
  CategoryRepository.get(tag[Category][Long](categoryId)).flatMap(_ match {
    case Some(category) => {
        CategoryRepository.remove(category.id).map(_.fold{InternalServerError("Server Error")}{_ => Redirect(routes.CategoryController.index())}).recover{
          case e:MySQLIntegrityConstraintViolationException => Redirect(routes.CategoryController.index())
        }
    }
    case None => {
      Future.successful(BadRequest("Invalid value"))
    }
  })
}
```

```scala
.recover{
          case e:MySQLIntegrityConstraintViolationException => Redirect(routes.CategoryController.index())
        }
```
コントローラーでFutureのエラーハンドリングを使ってみた
もっといい方法はありそう、リポジトリとかでもエラーハンドリングできるのかな？
try catchでもやってみたい

**Comment by yasuto2002** [comment]
### MysqlのCASCADE

```
ALTER TABLE `to_do` ADD FOREIGN KEY (`category_id`) REFERENCES `to_do_category` (`id`) ON DELETE CASCADE;
 ```
※要件に合えば

**Comment by yasuto2002** [comment]
```
import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
```
ここに例外が列挙されている？

**Comment by yasuto2002** [comment]
https://docs.oracle.com/javase/jp/6/api/java/sql/SQLIntegrityConstraintViolationException.html
JavaDocを見た方が良いとのとこ
