### ISSUE TITLE
lib.model~のEntityModelをそのままformにマッピングしたい

### ISSUE THREAD

**Issue by yasuto2002** [yasuto2002/todo-app#6]
unapplyを定義してなかったので定義
```
  def unapply(todo: Todo.WithNoId): Option[(Category.Id, String, String, Status)] = {
    Some((todo.v.category_id, todo.v.title, todo.v.body, todo.v.state))
  }
```
型エラーとかはない
ブラウザ
```
type mismatch;
 found   : play.api.data.Mapping[lib.model.Todo.WithNoId]
    (which expands to)  play.api.data.Mapping[ixias.model.Entity[Long with shapeless.tag.Tagged[lib.model.Todo],lib.model.Todo,ixias.model.IdStatus.Empty]]
 required: play.api.data.Mapping[lib.model.Todo]
```

シェル
```
play.sbt.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : play.api.data.Mapping[lib.model.Todo.WithNoId]
    (which expands to)  play.api.data.Mapping[ixias.model.Entity[Long with shapeless.tag.Tagged[lib.model.Todo],lib.model.Todo,ixias.model.IdStatus.Empty]]
 required: play.api.data.Mapping[lib.model.Todo]]
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
        at scala.Option.map(Option.scala:146)
        at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$1(PlayReload.scala:40)
        at scala.Option.map(Option.scala:146)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:35)
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:28)
        at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:63)
        at scala.util.Either$LeftProjection.map(Either.scala:569)
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:63)

```
`.verifying( `で躓いているよう

**Comment by yasuto2002** [comment]
### 違った
現状のマッピングの仕方だとただTodoをマッピングしているがTodoのapplyメソッドではWithNoIdを返しているのでおかしくなっている
```
Form(
23    mapping( 
24      "category_id" -> longNumber.transform[Category.Id]({id:Long => tag[Category][Long](id)},{categoryId:Category.Id => categoryId.toLong }),
25      "title" -> text.verifying(nonEmpty).verifying(maxLength(255)),
26      "body" -> text.verifying(nonEmpty).verifying(maxLength(255)),
27      "state" -> shortNumber.transform[lib.model.Todo.Status]({Todo.Status(_)},{_.code}),
```

**Comment by yasuto2002** [comment]
befor
```scala
val todoForm: Form[Todo] = Form(
```

after
```scala
val todoForm: Form[Todo.WithNoId] = Form(
```
